dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "**/bin/**/*"
  - "**/obj/**/*"
  - ".typo-ci.yml"
  - ".typo-ci.yml"
  - "**/*.vcxproj"
  - "**/.editorconfig"

# Any typos we should ignore?
excluded_words:
  - typoci
  - xaml
  - IntPtr
  - sln
  - NetCoreCProj
  - Dll
  - penet-project
  

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true